#/etc/X11/xorg.conf.d/30-touchpad.conf
# need restart x
Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lr"
    Option "NaturalScrolling" "on"
    Option "ScrollSpeed" "0.5"
EndSection
