C:\Users\xxx\AppData\Roaming\mpv
# 设置字幕字体
sub-font="微软雅黑"

# 设置字幕颜色为白色
sub-color="#FFFFFF"

# 设置字幕边框颜色为黑色
sub-border-color="#000000"

# 设置边框大小
sub-border-size=2

# 设置字幕阴影颜色
sub-shadow-color="#000000"
